name: Publish Draft

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create zip file for alpha release
        run: |
          mkdir ePub2-Notes
          cp plugin.png plugin.py plugin.xml ePub2-Notes/
          zip -r "ePub2-Notes_alpha.zip" ePub2-Notes

      - name: Create or Update Pre-release for alpha
        uses: softprops/action-gh-release@v1
        with:
          files: "ePub2-Notes_alpha.zip"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: |
          rm -rf ePub2-Notes
          rm ePub2-Notes_alpha.zip
